

version: '3'

services:
  api:
    build: 
      target: ${ENV}
      context: ./
      dockerfile: ./Dockerfile    
    environment:
      - ENV=${ENV}
      - NODE_ENV=${ENV}
    image: "ikouhaha888/vt6002cem_api"
    container_name: vt6002cem_api
    volumes:
      - ${B_V}/app
    ports:
      - "10888:10888"
      - "9229:9229"
      
      

 
